# Generated by Django 6.0.4 on 2026-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.TextField(max_length=60, unique=True)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
